version: '3.7'

services:
  rabbitmq-demo:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      - TCP_PORTS=15672, 5672
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq-test
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}]
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      com.datadoghq.ad.check_names: '["rabbitmq"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"rabbitmq_api_url": "http://%%host%%:15672/api/","username": "guest", "password":"guest"}]'
      com.datadoghq.ad.logs: '[{"source": "rabbitmq", "service": "rabbitmq-demo"}]'

  datadog-agent:
    image: datadog/agent:latest
    environment:
      - DD_SITE=datadoghq.eu
      - DD_API_KEY=FILL_IN_THIS_VALUE_WITH_YOUR_OWN_KEY
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_AC_EXCLUDE=name:datadog-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw

volumes:
  rabbitmq:
    driver: local